#
#
#properties 比 yml优先级高
#优先加载properties文件

server:
  port: 8080
  servlet:
    context-path: /springboot2

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources,src/main/java
      exclude: /WEB-INF/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: UTF-8
    mode: HTML



name:   zhangsan
url: www.abidu.com